version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quiz_app
    ports:
      - "5434:5432" # Map container's 5432 to host's 5434
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
