version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=quiz_app
      - DB_SSLMODE=disable
    restart: always
    networks:
      - quiz-network

  postgres:
    image: postgres:latest
    container_name: quiz_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quiz_app
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Add a volume for initialization scripts
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge

volumes:
  postgres-data:
