INSERT INTO questions (id, category, content, answer, created_at) VALUES (1, 'Celebrities', 'Which Indian actress starred in ''Quantico'' and ''Baywatch''?', 'Priyanka Chopra', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (2, 'Internet', 'Which Indian YouTuber is known for ''BB Ki Vines''?', 'Bhuvan Bam', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (3, 'Music', 'Which song by Tony Kakkar is often joked about for repetitive lyrics?', 'Coca Cola Tu', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (4, 'Music', 'Who composed the Oscar-winning song ''Jai Ho''?', 'A. R. Rahman', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (5, 'Celebrities', 'Who is known for the dialogue ''Pushpa, I hate tears''?', 'Rajesh Khanna', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (6, 'TV', 'Which TV serial revolves around the Maheshwari family in Udaipur?', 'Yeh Rishta Kya Kehlata Hai', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (7, 'Culture', 'Which Indian festival celebrates the triumph of good over evil and burning of Ravana?', 'Dussehra', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (8, 'Music', 'Which Punjabi singer had hits like ''Lamberghini'' and ''Brown Munde''?', 'AP Dhillon', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (9, 'Culture', 'Which traditional attire is worn by men in Kerala?', 'Mundu', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (10, 'Sports', 'Who is known as the ''Little Master''?', 'Sachin Tendulkar', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (11, 'Memes', 'Which Indian actor is associated with the ''Vimal Elaichi'' meme trend?', 'Ajay Devgn', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (12, 'Internet', 'Which Indian influencer is famous for ''Sasta Vicky Kaushal'' memes?', 'Hasnain Khan', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (13, 'Bollywood', 'Which actor played Bhallaladeva in ''Baahubali''?', 'Rana Daggubati', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (14, 'Celebrities', 'Which actor starred in the Hollywood film ''Life of Pi''?', 'Irrfan Khan', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (15, 'TV', 'Which superhero show aired in the 90s and starred Mukesh Khanna?', 'Shaktimaan', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (16, 'Celebrities', 'Which actor is nicknamed ''Greek God of Bollywood''?', 'Hrithik Roshan', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (17, 'Memes', 'From which show is the viral line ''Rasode mein kaun tha''?', 'Saath Nibhaana Saathiya', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (18, 'Music', 'Who composed ''Why This Kolaveri Di''?', 'Anirudh Ravichander', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (19, 'Sports', 'Which cricketer is nicknamed ''The Hitman''?', 'Rohit Sharma', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (20, 'Sports', 'Which footballer is captain of the Indian national team?', 'Sunil Chhetri', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (21, 'Celebrities', 'Who is the daughter of Sridevi and Boney Kapoor?', 'Janhvi Kapoor', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (22, 'TV', 'Which TV anchor is known for saying ''The nation wants to know''?', 'Arnab Goswami', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (23, 'Bollywood', 'Which movie features the iconic line ''Mogambo khush hua''?', 'Mr. India', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (24, 'Sports', 'Which Indian tennis player partnered with Leander Paes in doubles?', 'Mahesh Bhupathi', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (25, 'Culture', 'What is the name of India''s national song?', 'Vande Mataram', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (26, 'Celebrities', 'Which Indian actress is married to Virat Kohli?', 'Anushka Sharma', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (27, 'Bollywood', 'Which film won Best Picture at the Oscars and featured Indian actor Dev Patel?', 'Slumdog Millionaire', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (28, 'Memes', '''Kya karun main itni sundar hoon toh'' is associated with which influencer?', 'TikTok Girl - Garima Chaurasia', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (29, 'Celebrities', 'Who played ''Piku'' in the movie of the same name?', 'Deepika Padukone', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (30, 'Music', 'Who won the first season of Indian Idol?', 'Abhijeet Sawant', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (31, 'Memes', 'What viral phrase did Vipin Sahu shout while paragliding?', 'Land kara de', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (32, 'Sports', 'Who was India''s first female Olympic medalist?', 'Karnam Malleswari', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (33, 'Memes', '''Thala for a reason'' refers to which cricketer?', 'MS Dhoni', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (34, 'Internet', 'Which app did CarryMinati roast in a viral video?', 'TikTok', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (35, 'Bollywood', 'Who played the role of Alauddin Khilji in ''Padmaavat''?', 'Ranveer Singh', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (36, 'Culture', 'Which is India’s harvest festival in Punjab?', 'Lohri', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (37, 'Bollywood', 'In ''Kabir Singh'', what is the profession of the main character?', 'Doctor', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (38, 'Internet', 'Who is the founder of ''The Viral Fever'' (TVF)?', 'Arunabh Kumar', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (39, 'TV', 'Which Hindi serial had a character called ''Komolika''?', 'Kasautii Zindagii Kay', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (40, 'Memes', '''Hello friends, chai pi lo'' became a viral catchphrase from which platform?', 'WhatsApp', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (41, 'Celebrities', 'Which Indian actor voiced Mufasa in the Hindi version of ''The Lion King''?', 'Shah Rukh Khan', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (42, 'TV', 'Which quiz show aired on Doordarshan and was popular in the 90s?', 'Bournvita Quiz Contest', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (43, 'Sports', 'Who captained India to win the 2011 Cricket World Cup?', 'MS Dhoni', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (44, 'Sports', 'Which Indian won a gold medal at the 2020 Tokyo Olympics in javelin throw?', 'Neeraj Chopra', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (45, 'Celebrities', 'Who played the role of Sardar Udham in the 2021 film?', 'Vicky Kaushal', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (46, 'Internet', 'Which platform is known for ''ScoopWhoop'' and ''FilterCopy'' content?', 'YouTube', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (47, 'Culture', 'Which Indian classical dance originates from Tamil Nadu?', 'Bharatanatyam', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (48, 'TV', 'Which TV show features the character Jethalal?', 'Taarak Mehta Ka Ooltah Chashmah', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (49, 'Culture', 'What is the primary language spoken in West Bengal?', 'Bengali', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (50, 'Internet', 'Which educational YouTuber runs ''Physics Wallah''?', 'Alakh Pandey', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (51, 'Bollywood', 'Which 2018 movie popularized the character ''Murad'', a street rapper?', 'Gully Boy', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (52, 'Culture', 'In which festival do people smear colors on each other?', 'Holi', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (53, 'Memes', 'Which Bollywood scene turned meme involves ''Maa kasam, main dhoondh ke launga''?', 'Phir Hera Pheri', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (54, 'Music', 'Which rapper is associated with the track ''Machayenge''?', 'Emiway Bantai', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (55, 'TV', 'Who hosted ''Kaun Banega Crorepati''?', 'Amitabh Bachchan', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (56, 'Memes', 'Which Indian stand-up comedian''s joke ''Sakht Launda'' went viral?', 'Zakir Khan', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (57, 'Culture', 'Which city is known as the Pink City?', 'Jaipur', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (58, 'Internet', 'Which Indian streamer runs the channel ''Total Gaming''?', 'Ajjubhai', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (59, 'Bollywood', 'What is the name of the alien in the movie ''PK''?', 'PK', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (60, 'Celebrities', 'Who is known as King Khan in Bollywood?', 'Shah Rukh Khan', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (61, 'Sports', 'Which Indian bowler is known for his ''Boom Boom'' yorkers?', 'Jasprit Bumrah', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (62, 'Internet', 'Which comedy group created ''A Day with…'' sketches?', 'All India Bakchod', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (63, 'Music', 'Who is known as the Nightingale of India?', 'Lata Mangeshkar', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (64, 'Music', 'What is the title of Badshah''s viral track with Jacqueline Fernandez?', 'Paani Paani', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (65, 'Bollywood', 'Which movie launched Deepika Padukone''s Bollywood career?', 'Om Shanti Om', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (66, 'Music', 'Which artist is known for the song ''Mere Gully Mein''?', 'Divine', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (67, 'Internet', 'Which Indian platform became famous for meme sharing during 2020 lockdown?', 'Instagram', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (68, 'Sports', 'Which Indian boxer has a biopic titled after her?', 'Mary Kom', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (69, 'Memes', 'Which meme features a remix of a saree shop salesperson saying ''Just looking like a wow''?', 'Instagram Reel', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (70, 'Memes', 'What is the name of the ''screaming guy'' meme from ''Bigg Boss''?', 'Deepak Kalal', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (71, 'TV', 'In which show is the line ''Daya, darwaza tod do'' used?', 'CID', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (72, 'Music', 'Which song by Dhanush became India’s biggest viral song of 2011?', 'Why This Kolaveri Di', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (73, 'Internet', 'Who created the viral ''Pawri Ho Rahi Hai'' remix?', 'Yashraj Mukhate', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (74, 'Bollywood', 'In ''Dangal'', which sport is central to the story?', 'Wrestling', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (75, 'Sports', 'Which Indian badminton player has won a silver Olympic medal?', 'PV Sindhu', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (76, 'TV', 'What’s the name of the talent hunt show judged by Karan Johar and Malaika Arora?', 'India''s Got Talent', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (77, 'Culture', 'Which traditional dish is made during Eid in India?', 'Biryani', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (78, 'Bollywood', 'In ''3 Idiots'', what is Rancho''s real name?', 'Phunsukh Wangdu', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (79, 'TV', 'Which Indian reality show was adapted from ''Big Brother''?', 'Bigg Boss', '2025-03-29 13:22:46');
INSERT INTO questions (id, category, content, answer, created_at) VALUES (80, 'Culture', 'Which state is famous for Bihu dance?', 'Assam', '2025-03-29 13:22:46');