-- Now insert the formatted questions with gen_random_uuid() for the id
INSERT INTO questions (id, content, answer, category, created_at) VALUES
(gen_random_uuid(), 'Which Indian actress starred in ''Quantico'' and ''Baywatch''?', 'Priyanka Chopra', 'Celebrities', NOW()),
(gen_random_uuid(), 'Which Indian YouTuber is known for ''BB Ki Vines''?', 'Bhuvan Bam', 'Internet', NOW()),
(gen_random_uuid(), 'Which song by Tony Kakkar is often joked about for repetitive lyrics?', 'Coca Cola Tu', 'Music', NOW()),
(gen_random_uuid(), 'Who composed the Oscar-winning song ''Jai Ho''?', 'A. R. Rahman', 'Music', NOW()),
(gen_random_uuid(), 'Who is known for the dialogue ''Pushpa, I hate tears''?', 'Rajesh Khanna', 'Celebrities', NOW()),
(gen_random_uuid(), 'Which TV serial revolves around the Maheshwari family in Udaipur?', 'Yeh Rishta Kya Kehlata Hai', 'TV', NOW()),
(gen_random_uuid(), 'Which Indian festival celebrates the triumph of good over evil and burning of Ravana?', 'Dussehra', 'Culture', NOW()),
(gen_random_uuid(), 'Which Punjabi singer had hits like ''Lamberghini'' and ''Brown Munde''?', 'AP Dhillon', 'Music', NOW()),
(gen_random_uuid(), 'Which traditional attire is worn by men in Kerala?', 'Mundu', 'Culture', NOW()),
(gen_random_uuid(), 'Who is known as the ''Little Master''?', 'Sachin Tendulkar', 'Sports', NOW()),
(gen_random_uuid(), 'Which Indian actor is associated with the ''Vimal Elaichi'' meme trend?', 'Ajay Devgn', 'Memes', NOW()),
(gen_random_uuid(), 'Which Indian influencer is famous for ''Sasta Vicky Kaushal'' memes?', 'Hasnain Khan', 'Internet', NOW()),
(gen_random_uuid(), 'Which actor played Bhallaladeva in ''Baahubali''?', 'Rana Daggubati', 'Bollywood', NOW()),
(gen_random_uuid(), 'Which actor starred in the Hollywood film ''Life of Pi''?', 'Irrfan Khan', 'Celebrities', NOW()),
(gen_random_uuid(), 'Which superhero show aired in the 90s and starred Mukesh Khanna?', 'Shaktimaan', 'TV', NOW()),
(gen_random_uuid(), 'Which actor is nicknamed ''Greek God of Bollywood''?', 'Hrithik Roshan', 'Celebrities', NOW()),
(gen_random_uuid(), 'From which show is the viral line ''Rasode mein kaun tha''?', 'Saath Nibhaana Saathiya', 'Memes', NOW()),
(gen_random_uuid(), 'Who composed ''Why This Kolaveri Di''?', 'Anirudh Ravichander', 'Music', NOW()),
(gen_random_uuid(), 'Which cricketer is nicknamed ''The Hitman''?', 'Rohit Sharma', 'Sports', NOW()),
(gen_random_uuid(), 'Which footballer is captain of the Indian national team?', 'Sunil Chhetri', 'Sports', NOW()),
(gen_random_uuid(), 'Who is the daughter of Sridevi and Boney Kapoor?', 'Janhvi Kapoor', 'Celebrities', NOW()),
(gen_random_uuid(), 'Which TV anchor is known for saying ''The nation wants to know''?', 'Arnab Goswami', 'TV', NOW()),
(gen_random_uuid(), 'Which movie features the iconic line ''Mogambo khush hua''?', 'Mr. India', 'Bollywood', NOW()),
(gen_random_uuid(), 'Which Indian tennis player partnered with Leander Paes in doubles?', 'Mahesh Bhupathi', 'Sports', NOW()),
(gen_random_uuid(), 'What is the name of India''s national song?', 'Vande Mataram', 'Culture', NOW()),
(gen_random_uuid(), 'Which Indian actress is married to Virat Kohli?', 'Anushka Sharma', 'Celebrities', NOW()),
(gen_random_uuid(), 'Which film won Best Picture at the Oscars and featured Indian actor Dev Patel?', 'Slumdog Millionaire', 'Bollywood', NOW()),
(gen_random_uuid(), '''Kya karun main itni sundar hoon toh'' is associated with which influencer?', 'TikTok Girl - Garima Chaurasia', 'Memes', NOW()),
(gen_random_uuid(), 'Who played ''Piku'' in the movie of the same name?', 'Deepika Padukone', 'Celebrities', NOW()),
(gen_random_uuid(), 'Who won the first season of Indian Idol?', 'Abhijeet Sawant', 'Music', NOW()),
(gen_random_uuid(), 'What viral phrase did Vipin Sahu shout while paragliding?', 'Land kara de', 'Memes', NOW()),
(gen_random_uuid(), 'Who was India''s first female Olympic medalist?', 'Karnam Malleswari', 'Sports', NOW()),
(gen_random_uuid(), '''Thala for a reason'' refers to which cricketer?', 'MS Dhoni', 'Memes', NOW()),
(gen_random_uuid(), 'Which app did CarryMinati roast in a viral video?', 'TikTok', 'Internet', NOW()),
(gen_random_uuid(), 'Who played the role of Alauddin Khilji in ''Padmaavat''?', 'Ranveer Singh', 'Bollywood', NOW()),
(gen_random_uuid(), 'Which is India"s harvest festival in Punjab?', 'Lohri', 'Culture', NOW()),
(gen_random_uuid(), 'In ''Kabir Singh'', what is the profession of the main character?', 'Doctor', 'Bollywood', NOW()),
(gen_random_uuid(), 'Who is the founder of ''The Viral Fever'' (TVF)?', 'Arunabh Kumar', 'Internet', NOW()),
(gen_random_uuid(), 'Which Hindi serial had a character called ''Komolika''?', 'Kasautii Zindagii Kay', 'TV', NOW()),
(gen_random_uuid(), '''Hello friends, chai pi lo'' became a viral catchphrase from which platform?', 'WhatsApp', 'Memes', NOW()),
(gen_random_uuid(), 'Which Indian actor voiced Mufasa in the Hindi version of ''The Lion King''?', 'Shah Rukh Khan', 'Celebrities', NOW()),
(gen_random_uuid(), 'Which quiz show aired on Doordarshan and was popular in the 90s?', 'Bournvita Quiz Contest', 'TV', NOW()),
(gen_random_uuid(), 'Who captained India to win the 2011 Cricket World Cup?', 'MS Dhoni', 'Sports', NOW()),
(gen_random_uuid(), 'Which Indian won a gold medal at the 2020 Tokyo Olympics in javelin throw?', 'Neeraj Chopra', 'Sports', NOW()),
(gen_random_uuid(), 'Who played the role of Sardar Udham in the 2021 film?', 'Vicky Kaushal', 'Celebrities', NOW()),
(gen_random_uuid(), 'Which platform is known for ''ScoopWhoop'' and ''FilterCopy'' content?', 'YouTube', 'Internet', NOW()),
(gen_random_uuid(), 'Which Indian classical dance originates from Tamil Nadu?', 'Bharatanatyam', 'Culture', NOW()),
(gen_random_uuid(), 'Which TV show features the character Jethalal?', 'Taarak Mehta Ka Ooltah Chashmah', 'TV', NOW()),
(gen_random_uuid(), 'What is the primary language spoken in West Bengal?', 'Bengali', 'Culture', NOW()),
(gen_random_uuid(), 'Which educational YouTuber runs ''Physics Wallah''?', 'Alakh Pandey', 'Internet', NOW()),
(gen_random_uuid(), 'Which 2018 movie popularized the character ''Murad'', a street rapper?', 'Gully Boy', 'Bollywood', NOW()),
(gen_random_uuid(), 'In which festival do people smear colors on each other?', 'Holi', 'Culture', NOW()),
(gen_random_uuid(), 'Which Bollywood scene turned meme involves ''Maa kasam, main dhoondh ke launga''?', 'Phir Hera Pheri', 'Memes', NOW()),
(gen_random_uuid(), 'Which rapper is associated with the track ''Machayenge''?', 'Emiway Bantai', 'Music', NOW()),
(gen_random_uuid(), 'Who hosted ''Kaun Banega Crorepati''?', 'Amitabh Bachchan', 'TV', NOW()),
(gen_random_uuid(), 'Which Indian stand-up comedian''s joke ''Sakht Launda'' went viral?', 'Zakir Khan', 'Memes', NOW()),
(gen_random_uuid(), 'Which city is known as the Pink City?', 'Jaipur', 'Culture', NOW()),
(gen_random_uuid(), 'Which Indian streamer runs the channel ''Total Gaming''?', 'Ajjubhai', 'Internet', NOW()),
(gen_random_uuid(), 'What is the name of the alien in the movie ''PK''?', 'PK', 'Bollywood', NOW()),
(gen_random_uuid(), 'Who is known as King Khan in Bollywood?', 'Shah Rukh Khan', 'Celebrities', NOW()),
(gen_random_uuid(), 'Which Indian bowler is known for his ''Boom Boom'' yorkers?', 'Jasprit Bumrah', 'Sports', NOW()),
(gen_random_uuid(), 'Which comedy group created ''A Day with…'' sketches?', 'All India Bakchod', 'Internet', NOW()),
(gen_random_uuid(), 'Who is known as the Nightingale of India?', 'Lata Mangeshkar', 'Music', NOW()),
(gen_random_uuid(), 'What is the title of Badshah''s viral track with Jacqueline Fernandez?', 'Paani Paani', 'Music', NOW()),
(gen_random_uuid(), 'Which movie launched Deepika Padukone''s Bollywood career?', 'Om Shanti Om', 'Bollywood', NOW()),
(gen_random_uuid(), 'Which artist is known for the song ''Mere Gully Mein''?', 'Divine', 'Music', NOW()),
(gen_random_uuid(), 'Which Indian platform became famous for meme sharing during 2020 lockdown?', 'Instagram', 'Internet', NOW()),
(gen_random_uuid(), 'Which Indian boxer has a biopic titled after her?', 'Mary Kom', 'Sports', NOW()),
(gen_random_uuid(), 'Which meme features a remix of a saree shop salesperson saying ''Just looking like a wow''?', 'Instagram Reel', 'Memes', NOW()),
(gen_random_uuid(), 'What is the name of the ''screaming guy'' meme from ''Bigg Boss''?', 'Deepak Kalal', 'Memes', NOW()),
(gen_random_uuid(), 'In which show is the line ''Daya, darwaza tod do'' used?', 'CID', 'TV', NOW()),
(gen_random_uuid(), 'Which song by Dhanush became India"s biggest viral song of 2011?', 'Why This Kolaveri Di', 'Music', NOW()),
(gen_random_uuid(), 'Who created the viral ''Pawri Ho Rahi Hai'' remix?', 'Yashraj Mukhate', 'Internet', NOW()),
(gen_random_uuid(), 'In ''Dangal'', which sport is central to the story?', 'Wrestling', 'Bollywood', NOW()),
(gen_random_uuid(), 'Which Indian badminton player has won a silver Olympic medal?', 'PV Sindhu', 'Sports', NOW()),
(gen_random_uuid(), 'What"s the name of the talent hunt show judged by Karan Johar and Malaika Arora?', 'India''s Got Talent', 'TV', NOW()),
(gen_random_uuid(), 'Which traditional dish is made during Eid in India?', 'Biryani', 'Culture', NOW()),
(gen_random_uuid(), 'In ''3 Idiots'', what is Rancho''s real name?', 'Phunsukh Wangdu', 'Bollywood', NOW()),
(gen_random_uuid(), 'Which Indian reality show was adapted from ''Big Brother''?', 'Bigg Boss', 'TV', NOW()),
(gen_random_uuid(), 'Which state is famous for Bihu dance?', 'Assam', 'Culture', NOW());